### ISSUE TITLE
bundler: failed to load command: rails

### ISSUE THREAD

**Issue by tanertas** [tainewoo/redmine_custom_reminder#1]
I got similar error that you have mentioned here:
https://github.com/woblavobla/redmine_custom_reminder/issues/10

Did you find the cause of the problem? I got this:
```
bundler: failed to load command: rails (/home/redmine/redmine/bin/rails)
Bundler::GemNotFound: Could not find rake-13.0.1 in any of the sources
  /home/redmine/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/spec_set.rb:87:in `block in materialize'
  /home/redmine/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/spec_set.rb:81:in `map!'
  /home/redmine/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/spec_set.rb:81:in `materialize'
  /home/redmine/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/definition.rb:170:in `specs'
  /home/redmine/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/definition.rb:237:in `specs_for'
  /home/redmine/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/definition.rb:226:in `requested_specs'
  /home/redmine/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/runtime.rb:108:in `block in definition_method'
  /home/redmine/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/runtime.rb:20:in `setup'
  /home/redmine/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler.rb:107:in `setup'
  /home/redmine/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/setup.rb:20:in `<top (required)>'
  /home/redmine/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /home/redmine/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by tainewoo** [comment]
Hi @tanertas ,

sorry that i just back to this repo.
Yes, i used a different way to perform the task.
I use this command in the cron task, you can have a try:

/usr/local/bin/bundle exec /usr/local/bin/rails runner -e production "CustomRemindersJob.perform_now"
